const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('devLauncher', {
  getState: () => ipcRenderer.invoke('state:get'),
  addRoot: () => ipcRenderer.invoke('root:add'),
  removeRoot: (rootId) => ipcRenderer.invoke('root:remove', rootId),
  scanAll: () => ipcRenderer.invoke('scan:all'),
  updateProject: (projectId, patch) => ipcRenderer.invoke('project:update', projectId, patch),
  restoreProject: (projectId) => ipcRenderer.invoke('project:restore', projectId),
  relocateProject: (projectId) => ipcRenderer.invoke('project:relocate', projectId),
  startProject: (projectId) => ipcRenderer.invoke('process:start', projectId),
  stopProject: (projectId) => ipcRenderer.invoke('process:stop', projectId),
  restartProject: (projectId) => ipcRenderer.invoke('process:restart', projectId),
  stopAll: () => ipcRenderer.invoke('process:stop-all'),
  getSnapshot: (projectId) => ipcRenderer.invoke('process:snapshot', projectId),
  clearLogs: (projectId) => ipcRenderer.invoke('process:clear-logs', projectId),
  updateSettings: (patch) => ipcRenderer.invoke('settings:update', patch),
  saveGroup: (group) => ipcRenderer.invoke('group:save', group),
  removeGroup: (groupId) => ipcRenderer.invoke('group:remove', groupId),
  startGroup: (groupId) => ipcRenderer.invoke('group:start', groupId),
  stopGroup: (groupId) => ipcRenderer.invoke('group:stop', groupId),
  openUrl: (url) => ipcRenderer.invoke('shell:open-url', url),
  openPath: (targetPath) => ipcRenderer.invoke('shell:open-path', targetPath),
  copyText: (text) => ipcRenderer.invoke('clipboard:write', text),
  minimizeWindow: () => ipcRenderer.invoke('window:minimize'),
  toggleMaximizeWindow: () => ipcRenderer.invoke('window:toggle-maximize'),
  closeWindow: () => ipcRenderer.invoke('window:close'),
  getWindowState: () => ipcRenderer.invoke('window:get-state'),
  quit: () => ipcRenderer.invoke('app:quit'),
  onStateChanged: (callback) => ipcRenderer.on('state:changed', (_, value) => callback(value)),
  onScanProgress: (callback) => ipcRenderer.on('scan:progress', (_, value) => callback(value)),
  onProcessUpdate: (callback) => ipcRenderer.on('process:update', (_, value) => callback(value)),
  onStaleSession: (callback) => ipcRenderer.on('app:stale-session', (_, value) => callback(value)),
  onWindowMaximizedChanged: (callback) => ipcRenderer.on('window:maximized-changed', (_, value) => callback(value))
});
